name: yaml-presubmit
on:
  push:
    branches: ['master']
  pull_request:
    paths: ['**.yml', '**.yaml']

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: yamllint -d relaxed .
