name: java-presubmit
on:
  push:
    branches: ['master']
  pull_request:
    paths: ['java/**', '.github/workflows/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test with Maven
        run: mvn --batch-mode test
